module.exports={
    devServer:{
        host:'localhost',
        port:8081,
        proxy:{
            '/api':{
                target:'http://mall-pre.springboot.cn',
                changeOrigin:true,
                pathRewrite:{
                    '/api':''
                }
            }
        }
    },
    lintOnSave:false,
    productionSourceMap:false,
    chainWebpack:(config)=>{
        //删除编译后的预获取操作
        config.plugins.delete("prefetch")
    }
}